export const CONGRESS_OPTIONS = [
  {
    id: 'asco-2026',
    name: 'ASCO 2026',
    fullName: 'American Society of Clinical Oncology Annual Meeting 2026',
    location: 'Chicago, IL',
    date: 'May 29 – Jun 2, 2026',
    available: true,
  },
  {
    id: 'esmo-2025',
    name: 'ESMO 2025',
    fullName: 'European Society for Medical Oncology Congress 2025',
    location: 'Barcelona, Spain',
    date: 'Sep 12–16, 2025',
    available: true,
  },
  {
    id: 'asco-2025',
    name: 'ASCO 2025',
    fullName: 'American Society of Clinical Oncology Annual Meeting 2025',
    location: 'Chicago, IL',
    date: 'May 30 – Jun 3, 2025',
    available: true,
  },
  {
    id: 'trend-esmo-asco',
    name: 'Trend: ESMO → ASCO',
    fullName: 'Sentiment trend ESMO 2025 to ASCO 2026',
    location: '—',
    date: '—',
    available: true,
    isTrend: true,
  },
  {
    id: 'sabcs-2025',
    name: 'SABCS 2025',
    fullName: 'San Antonio Breast Cancer Symposium 2025',
    location: 'San Antonio, TX',
    date: 'Dec 9–13, 2025',
    available: true,
  },
  {
    id: 'eha-2026',
    name: 'EHA 2026',
    fullName: 'European Hematology Association Congress 2026',
    location: 'Milan, Italy',
    date: 'Jun 12–15, 2026',
    available: false,
    comingSoon: true,
  },
  {
    id: 'ectrims-2026',
    name: 'ECTRIMS 2026',
    fullName: 'European Committee for Treatment and Research in Multiple Sclerosis 2026',
    location: 'TBD',
    date: 'September 2026',
    available: false,
    comingSoon: true,
  },
];
