export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'Infusion-center inertia slowing Phesgo SC transition',
    priority: 'High',
    lpRefs: ['LP1'],
    moRefs: ['MO1'],
    recurrence: 4,
    recency: '2026-05',
    summary: 'Community oncology infusion centers continue defaulting to IV trastuzumab + pertuzumab out of workflow habit, even where Phesgo is formulary-approved. Nurses cite unfamiliarity with SC administration protocols and fear of slowing throughput.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community oncologist', location: 'Houston, TX', quote: 'My infusion nurses just know the IV routine. Phesgo SC is theoretically simpler but changing their workflow has been harder than I expected.', date: '2026-05-08' },
      { type: 'Ad board', role: 'Breast oncologist', location: 'Chicago, IL', quote: 'The chair time reduction argument is compelling but the IV drip is already set up. Someone has to champion the switch at the center level.', date: '2026-04-18' },
      { type: 'MSL interaction', role: 'Infusion center nurse manager', location: 'Atlanta, GA', quote: 'We need a simple step-by-step SC administration card we can laminate and post at every chair.', date: '2026-05-15' },
      { type: 'MSL interaction', role: 'Community oncologist', location: 'Phoenix, AZ', quote: 'Three or four centers around me have switched and they love it. I just need one of my own nurses to champion it internally.', date: '2026-05-21' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'ASCO 2026 abstracts reshaping HER2+ sequencing discussions',
    priority: 'High',
    lpRefs: ['LP2'],
    moRefs: ['MO1'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'HER2CLIMB-02 and DESTINY-Breast06 data presented at ASCO 2026 are prompting oncologists to revisit sequencing of T-DXd versus Phesgo in the early and metastatic settings. MSLs report increased competitive questions at booth and in interactions.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'Breast oncologist', location: 'ASCO 2026', quote: 'The DESTINY-Breast06 subgroup data is going to move the goal posts on what "HER2-low" means in early BC. Where does Phesgo fit in that framing?', date: '2026-06-02' },
      { type: 'MSL interaction', role: 'Academic breast oncologist', location: 'Boston, MA', quote: "I'm getting questions from my residents about sequencing SC pertuzumab-based doublets vs. ADC monotherapy. I need a clear algorithm.", date: '2026-06-04' },
      { type: 'Ad board', role: 'Breast cancer KOL', location: 'Virtual', quote: "The neoadjuvant Phesgo data is still foundational — DESTINY doesn't touch that space yet. We need to be clear about where Phesgo's home is.", date: '2026-05-29' },
    ],
    status: 'Validated',
    confidenceScore: 0.88,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'Polivy positioning unclear vs. tafasitamab + loncastuximab in R/R DLBCL',
    priority: 'High',
    lpRefs: ['LP3'],
    moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'Haematologists treating relapsed/refractory DLBCL report confusion about when to use Polivy vs. tafasitamab-lenalidomide vs. loncastuximab, particularly in patients who are CAR-T ineligible. Clear patient-selection criteria are the most-requested resource.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community haematologist', location: 'Dallas, TX', quote: 'I use Polivy-BR when I\'m bridging to CAR-T. But for the patient who can\'t get to transplant, I\'m honestly not sure what to reach for first.', date: '2026-05-06' },
      { type: 'Ad board', role: 'Academic haematologist', location: 'New York, NY', quote: 'We need a practical algorithm — fitness, prior lines, CAR-T eligibility — that tells a community doctor which agent to default to.', date: '2026-04-22' },
      { type: 'MSL interaction', role: 'Lymphoma specialist', location: 'Seattle, WA', quote: 'If there were head-to-head data I\'d feel confident. Without it, everything is network meta-analysis and opinion.', date: '2026-05-14' },
    ],
    status: 'Validated',
    confidenceScore: 0.84,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'Progressive MS physicians under-confident on Ocrevus PPMS durability',
    priority: 'Medium',
    lpRefs: ['LP4'],
    moRefs: ['MO3'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'Neurologists managing PPMS patients report uncertainty about long-term disability progression outcomes with Ocrevus beyond 3-year data. Real-world open-label extension data requested; some are defaulting to watchful waiting for higher-disability patients.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Neurologist', location: 'Minneapolis, MN', quote: 'The ORATORIO data convinced me on early PPMS. But what does the 7-year disability curve actually look like? I need to counsel my patients on lifetime burden.', date: '2026-04-09' },
      { type: 'Congress debrief', role: 'MS specialist', location: 'ECTRIMS 2025', quote: 'The open-label extension was promising but not widely cited. We should be leading with that data in every conversation about progressive MS.', date: '2025-09-23' },
    ],
    status: 'Triaged',
    confidenceScore: 0.76,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Vabysmo bispecific mechanism underappreciated in retina community',
    priority: 'Medium',
    lpRefs: ['LP5'],
    moRefs: ['MO4'],
    recurrence: 2,
    recency: '2026-04',
    summary: "Retinal specialists acknowledge Vabysmo's clinical data but many cannot articulate the Ang-2/VEGF-A dual mechanism or the rationale for extended dosing intervals. The mechanism is the key differentiating story and it is not landing.",
    sourceInsights: [
      { type: 'MSL interaction', role: 'Retinal specialist', location: 'Miami, FL', quote: 'I switched some patients to Vabysmo and the 16-week intervals are real. But when I explain why to residents I struggle with the Ang-2 component.', date: '2026-04-17' },
      { type: 'Ad board', role: 'Academic retinal specialist', location: 'Virtual', quote: 'Most of my community colleagues think Vabysmo is just another anti-VEGF. The Ang-2 story has to land for the dosing interval argument to make sense.', date: '2026-03-28' },
    ],
    status: 'Triaged',
    confidenceScore: 0.71,
    provenance: 'synthesized',
  },
  {
    id: 'AI6',
    title: 'Pediatric hemophilia A specialists need long-term joint outcome data',
    priority: 'Medium',
    lpRefs: ['LP6'],
    moRefs: ['MO5'],
    recurrence: 2,
    recency: '2026-03',
    summary: 'Pediatric haematologists treating young patients with hemophilia A are supportive of emicizumab prophylaxis but request long-term joint health data to counsel families on lifetime commitment and risk of inhibitor development.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Pediatric haematologist', location: 'Toronto, Canada', quote: 'I start almost everyone on emicizumab now. But parents ask what the MRI of their child\'s joints will look like at age 30. I can\'t answer that yet.', date: '2026-03-12' },
      { type: 'Med Info query', role: 'Pediatric haematologist', location: 'London, UK', quote: 'Is there anything beyond the 3-year HAVEN data on joint outcomes in the very young patient?', date: '2026-03-28' },
    ],
    status: 'Captured',
    confidenceScore: 0.67,
    provenance: 'synthesized',
  },
  {
    id: 'AI7',
    title: 'Community oncologists request concise Phesgo biosimilar-differentiation brief',
    priority: 'High',
    lpRefs: ['LP1', 'LP2'],
    moRefs: ['MO1'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'With biosimilar trastuzumab widely adopted, community oncologists are now asking for a clear, brief narrative distinguishing Phesgo (fixed-dose SC combination) from biosimilar trastuzumab + pertuzumab IV. Current materials read as overly academic.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community oncologist', location: 'Nashville, TN', quote: 'I know Phesgo is not just a biosimilar play — it\'s the SC FDC. But a two-page "here\'s the difference" sheet is what I can hand a colleague who asks.', date: '2026-05-19' },
      { type: 'Ad board', role: 'Community oncologist', location: 'Denver, CO', quote: 'The value story for Phesgo needs to be in plain language. We don\'t need 40 slides — we need one clear paragraph.', date: '2026-04-30' },
      { type: 'MSL interaction', role: 'Oncology pharmacist', location: 'Philadelphia, PA', quote: 'Pharmacy committees want to know the formulary position. A simple Phesgo vs. biosimilar combo comparison would answer most of their questions.', date: '2026-05-07' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.86,
    provenance: 'synthesized',
  },
];
