// KOL roster — Roche demo. 18 real KOLs across breast oncology, lymphoma,
// neurology (MS), ophthalmology, and haematology (hemophilia A).
// Note: Franck Morschhauser is the divergence KOL (declining Polivy alignment).

export const KOL_DATA = [
  // ── Breast Cancer / Phesgo ──────────────────────────────────────────────────
  {
    id: 'kol-1',
    name: 'Sara A. Hurvitz',
    institution: 'University of Washington / Fred Hutchinson Cancer Center',
    city: 'Seattle',
    country: 'USA',
    region: 'North America',
    specialty: 'Breast Oncology',
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['phesgo'],
    recentInteractions: 13,
    publications: 241,
    focusAreas: ['HER2+ Breast Cancer', 'Neoadjuvant Therapy', 'ADC Sequencing', 'Clinical Trials'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Maintain quarterly strategic advisory relationship. Engage on Phesgo neoadjuvant evidence vs. T-DXd and ASCO 2026 sequencing debate. Leverage as primary US voice for Phesgo SC adoption narrative in community oncology.',
  },
  {
    id: 'kol-2',
    name: 'Javier Cortés',
    institution: 'IOB Institute of Oncology, Hospital Quirónsalud Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    specialty: 'Breast Oncology',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['phesgo'],
    recentInteractions: 11,
    publications: 387,
    focusAreas: ['HER2+ mBC', 'Triple-Negative BC', 'Immunotherapy Combinations', 'SC Administration'],
    conferenceAppearances: 14,
    recommendedStrategy: 'Deepen engagement on EU5 HER2+ treatment landscape and SC Phesgo adoption patterns. Key voice in ESMO biosimilar differentiation discussions. Support publication strategy on real-world SC Phesgo outcomes.',
  },
  {
    id: 'kol-3',
    name: 'Sherene Loi',
    institution: 'Peter MacCallum Cancer Centre / University of Melbourne',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Asia-Pacific',
    specialty: 'Breast Oncology',
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['phesgo'],
    recentInteractions: 10,
    publications: 198,
    focusAreas: ['HER2+ Breast Cancer', 'Tumour Immunology', 'Biomarkers', 'Early-Stage BC'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Engage on early-stage HER2+ pCR data and long-term survival outcomes with Phesgo neoadjuvant. Leverage for APAC market Phesgo thought-leadership programme and guideline advocacy.',
  },
  {
    id: 'kol-4',
    name: 'Nadia Harbeck',
    institution: 'Brustzentrum, LMU Klinikum München',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    specialty: 'Breast Oncology',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['phesgo'],
    recentInteractions: 9,
    publications: 312,
    focusAreas: ['HER2+ BC', 'HR+/HER2+ Overlap', 'Treatment Algorithms', 'Guidelines'],
    conferenceAppearances: 12,
    recommendedStrategy: 'Key partner for AGO guideline influence and German market. Engage on HR+/HER2+ subgroup data and Phesgo sequencing vis-à-vis CDK4/6 combinations. Priority voice for EU5 SC adoption.',
  },
  {
    id: 'kol-5',
    name: 'George W. Sledge Jr.',
    institution: 'Stanford University School of Medicine',
    city: 'Stanford',
    country: 'USA',
    region: 'North America',
    specialty: 'Breast Oncology',
    influenceScore: 88,
    engagementTier: 'Tier 2',
    productAlignment: ['phesgo'],
    recentInteractions: 7,
    publications: 421,
    focusAreas: ['HER2+ BC', 'Metastatic BC', 'Precision Oncology', 'Drug Development'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Engage at ASCO scientific exchange level. Align on long-term survival data for HER2+ mBC and the Phesgo backbone narrative. Valuable for advisory input on precision oncology evidence standards.',
  },
  {
    id: 'kol-6',
    name: 'Arlene Chan',
    institution: 'Breast Cancer Research Centre–WA',
    city: 'Perth',
    country: 'Australia',
    region: 'Asia-Pacific',
    specialty: 'Breast Oncology',
    influenceScore: 83,
    engagementTier: 'Tier 2',
    productAlignment: ['phesgo'],
    recentInteractions: 6,
    publications: 167,
    focusAreas: ['HER2+ BC', 'Patient-Reported Outcomes', 'SC Tolerability', 'Community Oncology'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Leverage for patient-reported outcome data collection on SC Phesgo. Strong community oncology voice in APAC. Engage on Phesgo tolerability and quality-of-life narrative.',
  },
  // ── Lymphoma / Polivy ───────────────────────────────────────────────────────
  {
    id: 'kol-7',
    name: 'Gilles Salles',
    institution: 'Memorial Sloan Kettering Cancer Center',
    city: 'New York',
    country: 'USA',
    region: 'North America',
    specialty: 'Haematology / Lymphoma',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['polivy'],
    recentInteractions: 12,
    publications: 298,
    focusAreas: ['DLBCL', 'Follicular Lymphoma', 'B-Cell NHL', 'CAR-T Therapy'],
    conferenceAppearances: 13,
    recommendedStrategy: 'Strategic advisory partner on DLBCL first-line treatment evolution. Engage on POLARIX real-world data and the Polivy positioning in CAR-T bridging vs. eligible contexts. Key voice for US guidelines.',
  },
  {
    id: 'kol-8',
    name: 'Michael Crump',
    institution: 'Princess Margaret Cancer Centre',
    city: 'Toronto',
    country: 'Canada',
    region: 'North America',
    specialty: 'Haematology / Lymphoma',
    influenceScore: 87,
    engagementTier: 'Tier 1',
    productAlignment: ['polivy'],
    recentInteractions: 9,
    publications: 189,
    focusAreas: ['DLBCL', 'R/R NHL', 'Transplant Eligibility', 'Supportive Care'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Engage on real-world Polivy outcomes in Canadian centres and the CAR-T access gap in Canada as a context for Polivy bridge use. Valuable for patient selection algorithm input.',
  },
  {
    id: 'kol-9',
    name: 'Nathan Fowler',
    institution: 'University of Texas MD Anderson Cancer Center',
    city: 'Houston',
    country: 'USA',
    region: 'North America',
    specialty: 'Haematology / Lymphoma',
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['polivy'],
    recentInteractions: 10,
    publications: 214,
    focusAreas: ['Follicular Lymphoma', 'DLBCL', 'Indolent NHL', 'Novel Combinations'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Priority engagement on Polivy in follicular lymphoma and the emerging 2L+ FL opportunity. Leverage relationship at ASH and ASCO for FL advisory board leadership.',
  },
  {
    id: 'kol-10',
    name: 'Tanya Siddiqi',
    institution: 'City of Hope National Medical Center',
    city: 'Duarte',
    country: 'USA',
    region: 'North America',
    specialty: 'Haematology / Lymphoma',
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['polivy'],
    recentInteractions: 7,
    publications: 143,
    focusAreas: ['DLBCL', 'CLL', 'BTK Inhibitors', 'Cellular Therapy'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Engage on Polivy integration within a CAR-T programme at a high-volume centre. Valuable perspective on sequencing Polivy before cellular therapy and the role of fitness assessment.',
  },
  {
    id: 'kol-11',
    name: 'Franck Morschhauser',
    institution: 'CHU de Lille, Université de Lille',
    city: 'Lille',
    country: 'France',
    region: 'Europe',
    specialty: 'Haematology / Lymphoma',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['polivy'],
    recentInteractions: 5,
    publications: 176,
    focusAreas: ['FL', 'DLBCL', 'Anti-CD20 Combinations', 'Clinical Trials'],
    conferenceAppearances: 9,
    recommendedStrategy: 'URGENT: Declining alignment — recent publications and congress presentations position tafasitamab + lenalidomide ahead of Polivy-BR in CAR-T ineligible patients. Schedule scientific exchange on POLARIX extension data and unmet need framing before EHA 2026.',
  },
  // ── Multiple Sclerosis / Ocrevus ────────────────────────────────────────────
  {
    id: 'kol-12',
    name: 'Stephen L. Hauser',
    institution: 'University of California San Francisco',
    city: 'San Francisco',
    country: 'USA',
    region: 'North America',
    specialty: 'Neurology',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['ocrevus'],
    recentInteractions: 11,
    publications: 634,
    focusAreas: ['Multiple Sclerosis', 'Neuroimmunology', 'Anti-CD20 Therapy', 'Progressive MS'],
    conferenceAppearances: 15,
    recommendedStrategy: 'Maintain premier advisory relationship. Key scientific architect of the anti-CD20 MS narrative. Engage on PPMS open-label extension data and the SC Ocrevus (Ocrevus Zunovo) transition strategy.',
  },
  {
    id: 'kol-13',
    name: 'Xavier Montalban',
    institution: 'Hospital Universitari Vall d\'Hebron',
    city: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    specialty: 'Neurology',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['ocrevus'],
    recentInteractions: 10,
    publications: 487,
    focusAreas: ['MS Treatment Algorithms', 'PPMS', 'Disability Progression', 'Biomarkers'],
    conferenceAppearances: 14,
    recommendedStrategy: 'Priority engagement for European guideline influence and ECTRIMS. Champion for progressive MS evidence. Engage on disability endpoint data and long-term outcomes narrative for higher-disability PPMS patients.',
  },
  {
    id: 'kol-14',
    name: 'Jiwon Oh',
    institution: 'St. Michael\'s Hospital, University of Toronto',
    city: 'Toronto',
    country: 'Canada',
    region: 'North America',
    specialty: 'Neurology',
    influenceScore: 79,
    engagementTier: 'Tier 2',
    productAlignment: ['ocrevus'],
    recentInteractions: 6,
    publications: 98,
    focusAreas: ['MS', 'Progressive MS', 'MRI Outcomes', 'Clinical Practice Guidelines'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Engage on Canadian PPMS practice patterns and barriers to Ocrevus initiation at higher disability levels. Strong voice in North American guideline working groups.',
  },
  // ── Ophthalmology / Vabysmo ─────────────────────────────────────────────────
  {
    id: 'kol-15',
    name: 'Pravin U. Dugel',
    institution: 'Retinal Consultants of Arizona / Spectra Eye Institute',
    city: 'Phoenix',
    country: 'USA',
    region: 'North America',
    specialty: 'Ophthalmology',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['vabysmo'],
    recentInteractions: 8,
    publications: 312,
    focusAreas: ['nAMD', 'DME', 'Anti-VEGF Therapy', 'Bispecific Mechanisms'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Strategic advisory partner on Vabysmo extended interval narrative. Leverage clinical experience with 16-week dosing for academic publications and community retina education programmes. Primary US voice for Ang-2/VEGF-A bispecific mechanism education.',
  },
  {
    id: 'kol-16',
    name: 'Peter K. Kaiser',
    institution: 'Cole Eye Institute, Cleveland Clinic',
    city: 'Cleveland',
    country: 'USA',
    region: 'North America',
    specialty: 'Ophthalmology',
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['vabysmo'],
    recentInteractions: 6,
    publications: 198,
    focusAreas: ['nAMD', 'Retinal Vascular Disease', 'Anti-VEGF', 'RCT Methodology'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Engage on YOSEMITE/RHINE extension outcomes and real-world Vabysmo interval extension data. Valuable for clinical trial methodology conversations and community retina education.',
  },
  // ── Haematology / Hemlibra ──────────────────────────────────────────────────
  {
    id: 'kol-17',
    name: 'Guy Young',
    institution: 'Children\'s Hospital Los Angeles / Keck School of Medicine, USC',
    city: 'Los Angeles',
    country: 'USA',
    region: 'North America',
    specialty: 'Paediatric Haematology',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['hemlibra'],
    recentInteractions: 9,
    publications: 287,
    focusAreas: ['Hemophilia A', 'Pediatric Prophylaxis', 'Inhibitors', 'Gene Therapy'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Primary partner for pediatric emicizumab evidence strategy. Engage on HAVEN long-term extension data and joint health outcomes to address the pediatric evidence gap (AI6). Key advisory input for LP6 listening priority.',
  },
  {
    id: 'kol-18',
    name: 'Flora Peyvandi',
    institution: 'Fondazione IRCCS Ca\' Granda Ospedale Maggiore Policlinico, University of Milan',
    city: 'Milan',
    country: 'Italy',
    region: 'Europe',
    specialty: 'Haematology',
    influenceScore: 85,
    engagementTier: 'Tier 2',
    productAlignment: ['hemlibra'],
    recentInteractions: 7,
    publications: 334,
    focusAreas: ['Hemophilia A', 'Von Willebrand Disease', 'Rare Coagulation Disorders', 'Real-World Evidence'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Engage on European hemophilia A treatment landscape and emicizumab real-world evidence generation. Strong voice at WFH and EHA for Hemlibra prophylaxis positioning. Partner for Italian market and EU guidelines.',
  },
];
