export const PREDICTIVE_SIGNALS = [
  {
    id: 'ps-1',
    agent: 'ARIA',
    signal: 'DESTINY-Breast06 subgroup data reframing HER2-low early BC treatment',
    currentState: 'ASCO 2026 abstract 1002 shows T-DXd benefit extending into HER2-ultralow, prompting oncologists to reconsider where Phesgo anchors in the neoadjuvant and adjuvant settings.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Brief all MSLs on Phesgo neoadjuvant strength in HER2 3+ and the distinct patient population Phesgo serves vs. T-DXd. Prepare reactive talking points.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-2',
    agent: 'NOVA',
    signal: 'MO5 (Hemlibra pediatric evidence) at Gap — 0 qualifying insights this cycle',
    currentState: 'No insights have been captured against MO5 in 3 months. Pediatric hemophilia specialists are actively requesting long-term joint data that the field team is not currently equipped to provide.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'high',
    requiredAction: 'Assign LP6 listening priority to at least two MSLs; initiate pediatric haematology advisory board agenda item on HAVEN long-term extension data.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-3',
    agent: 'LUCA',
    signal: 'Franck Morschhauser increasingly citing tafasitamab data in DLBCL presentations',
    currentState: 'Two recent conference talks and one peer-reviewed publication show Dr. Morschhauser positioning tafasitamab + lenalidomide ahead of Polivy-BR in CAR-T ineligible relapsed DLBCL. Alignment score declining: 73 → 61 over 60 days.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Schedule scientific exchange on POLARIX real-world extension data. Prepare advisory discussion on unmet need in CAR-T ineligible population.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-4',
    agent: 'NOVA',
    signal: 'Insight AI1 (SC inertia) has recurred 4× — recurrence threshold exceeded',
    currentState: 'Community oncology infusion-center resistance to Phesgo SC has been captured 4 separate times this cycle (Prioritised). A1 (SC quick-reference card) is Started but not yet deployed.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Accelerate A1 delivery and add nurse-manager co-creation component. Flag as Q3 MO1 priority at next field medical review.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-5',
    agent: 'LUCA',
    signal: '3 emerging breast cancer KOLs crossed the watch threshold',
    currentState: 'Three early-career academic breast oncologists — all presenting at ASCO 2026 — show rising publication cadence (+55% vs. prior 6 months) and are not on the current Phesgo engagement list.',
    trajectory: 'rising',
    timeToImpact: '6–12 months',
    confidence: 'medium',
    requiredAction: 'Add to LUCA watch list; assign MSL for initial outreach post-ASCO 2026.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
];
